services:
  backend:
    build:
      context: ./backend
    ports:
      - "5500:5500"
    volumes:
      - sqlite-data:/usr/src/app/database
      - pdf-data:/usr/src/app/pdfs
    environment:
      - JWT_SECRET=zLhqQZ9j2XsJdEkW3mRp7TvN8fA6yGcB
      - JWT_REFRESH_SECRET=bPdS5vF7mK2jL9aR4eX8qW3tZ6yUcG1h
      - NODE_ENV=development
    networks:
      - app-network
    # Initialisation des répertoires au démarrage du conteneur
    command: >
      bash -c "
        mkdir -p /usr/src/app/database /usr/src/app/pdfs &&
        chmod -R 777 /usr/src/app/database /usr/src/app/pdfs &&
        touch /usr/src/app/database/esign.sqlite &&
        chmod 777 /usr/src/app/database/esign.sqlite &&
        node src/server.js
      "


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  sqlite-data:
  pdf-data:

networks:
  app-network:
    driver: bridge
