version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"

  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
